### ISSUE TITLE
input$X_data won't update on adding/removing row

### ISSUE THREAD

**Issue by jeanantoinedasilva** [dreamRs/toastui#16]
Hello,

The value input$X_data is not updated when adding/removing rows using grid_proxy_add_row/grid_proxy_delete_row.

I think the event listener does not take into account the appendRow event.

JA

**Comment by pvictor** [comment]
Indeed the event `afterChange` isn't triggered, but there does not seem to be any event triggered by `appendRow` or `removeRow`. So now input is updated when shiny receive one of those two custom message.

Victor

**Comment by jeanantoinedasilva** [comment]
Thanks !
