### ISSUE TITLE
Calendar language

### ISSUE THREAD

**Issue by pablotis** [dreamRs/toastui#19]
Hi there! is there an argument to set the calendar language, for example, to spanish?

Thanks in advance

**Comment by pvictor** [comment]
Hello, 

There's no global options to  change language, but you can change text through options and [template functionnality](https://nhn.github.io/tui.calendar/latest/Template).
Here's an example:

```r
calendar(
  navigation = TRUE, 
  navOpts = navigation_options(today_label = "Aujourd'hui"),
  useCreationPopup = TRUE,
  isReadOnly = FALSE
) %>%
  cal_month_options(
    startDayOfWeek  = 1, 
    daynames = c("Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"),
    narrowWeekend = TRUE
  ) %>% 
  cal_template(
    popupSave = JS("function() {return 'Sauvegarder';}")
```
Which give:

![Screenshot 2022-02-16 at 10-17-27 Screenshot](https://user-images.githubusercontent.com/4415580/154233652-4bd17478-b4d6-4d9f-a377-ee44366a88b2.png)

Victor

**Comment by pablotis** [comment]
That's great, thanks a lot!
