### ISSUE TITLE
Intraday schedules not rendered on Safari

### ISSUE THREAD

**Issue by msaltieri** [dreamRs/toastui#2]
Hello @pvictor! First of all, congratulations for this great package.

I'm running the following example:

```
library(shiny)
library(toastui)

ui <- fluidPage(
    tags$h2("Add, Update and Delete schedule interactively"),

    tags$p(
        "Click on the calendar to create a new schedule",
        "then you will be able to edit or delete it."
    ),

    calendarOutput("my_calendar")
)

server <- function(input, output) {

    output$my_calendar <- renderCalendar({
        cal <- calendar(
            data = cal_demo_data(),
            defaultDate = Sys.Date(),
            useNavigation = TRUE,
            isReadOnly = FALSE,
            useCreationPopup = TRUE
        )
    })

    observeEvent(input$my_calendar_add, {
        str(input$my_calendar_add)
        cal_proxy_add("my_calendar", input$my_calendar_add)
    })

    observeEvent(input$my_calendar_update, {
        str(input$my_calendar_update)
        cal_proxy_update("my_calendar", input$my_calendar_update)
    })

    observeEvent(input$my_calendar_delete, {
        str(input$my_calendar_delete)
        cal_proxy_delete("my_calendar", input$my_calendar_delete)
    })

}

if (interactive())
    shinyApp(ui = ui, server = server)
```

The problem is that - on Safari - the intraday schedules are not rendered properly:

<img width="1920" alt="Schermata 2021-05-21 alle 18 47 07" src="https://user-images.githubusercontent.com/26568338/119171599-144d3700-ba65-11eb-91b5-5d398148d3c6.png">

The same problem apparently doesn't occur on other browsers like Firefox, for example.

Do you have any idea of how to solve it?

**Comment by pvictor** [comment]
I don't have access to Safari to test...
Is the same problem occurs here : https://ui.toast.com/tui-calendar ?

Can you try:

```r
calendar(useDetailPopup = TRUE) %>%
  cal_schedules(
    title = "My schedule",
    body = "Some detail about it",
    start = "2021-05-03T00:00:00+00:00",
    end = "2021-05-05T00:00:00+00:00",
    category = "allday"
  )
```

**Comment by msaltieri** [comment]
Hello @pvictor, thanks for the fast answer!

My bad, I found where the problem is.

I was formatting the timestamps like `%Y-%m-%d %H:%M:%S` without the `T`. Incredibly, this way the rendering of the widget is perfect on Firefox.

Anyway, with the correct `%Y-%m-%dT%H:%M:%S` formatting the issue is completely resolved!
