### ISSUE TITLE
Calendar - incorrect date range displayed when using navigation

### ISSUE THREAD

**Issue by masanni** [dreamRs/toastui#20]
Hello, when trying to use navigation options with buttons in the following example where it is possible to switch between different calendar views, the date range displayed in the daily and weekly view is completely messed up. I cannot figure out why it happens and would appreciate any help.

``` library(shiny)

ui <- fluidPage(
  tags$h2("Change calendar view"),
  radioButtons(
    inputId = "view",
    label = "Change view:",
    choices = c("day", "week", "month"),
    inline = TRUE
  ),
  calendarOutput(outputId = "my_calendar")
)

server <- function(input, output, session) {

  output$my_calendar <- renderCalendar({
    calendar(view = "day", scheduleView = "allday", navigation = TRUE) %>%
      cal_schedules(
        title = "Today planning",
        start = Sys.Date(),
        end = Sys.Date(),
        category = "allday"
      )
  })

  observeEvent(
    input$view,
    cal_proxy_view("my_calendar", input$view),
    ignoreInit = TRUE
  )

}


if (interactive())
  shinyApp(ui, server)

```

![week_view](https://user-images.githubusercontent.com/34754592/154854003-e19825f1-85e2-49a3-9cfd-6f4f4097b9c5.JPG)

**Comment by pvictor** [comment]
Thanks for reporting. That's fixed if you re-install from GitHub.

Victor

**Comment by masanni** [comment]
Perfect! Thank you Victor for fixing it so quickly.
