### ISSUE TITLE
How to update schedule (unique id) & modify schedule properties

### ISSUE THREAD

**Issue by jbwzzang** [dreamRs/toastui#21]

**Comment by jbwzzang** [comment]
1. How to update schedule (data flow)
   - when i add schedule. (using calendar`s "useCreationPopup option), How can i check or read the "id".
      or Please help me how to update calendar schedule. 
     e.g add schedule (O)
           update schedule (id O)

2. How to modify schedule properties when I add schedule. 
    default is "subject, location start, end, All day, Status (busy or free)

**Comment by jbwzzang** [comment]
I`ll ask later

**Comment by pvictor** [comment]
I didn't have time to read the issue, you can leave it open, I will look at it as soon as I can.

Victor
