### ISSUE TITLE
Shiny does not notify when clicking for the second time the same element

### ISSUE THREAD

**Issue by fsty** [dreamRs/toastui#26]
Hi! 
Thank you for this package! 

I notice that Shiny is not reacting when I click the same element  (of calendar or grid ) for the second time : 
Here an example : If I click a cell for the second time the modal does not appear : 
```
library(shiny)
library(toastui)

ui <- fluidPage(
  tags$h2("datagrid click"),
  datagridOutput("grid")
)

server <- function(input, output, session) {
  
  df <- data.frame(
    index = 1:12,
    month = month.name,
    letters = letters[1:12]
  )
  
  output$grid <- renderDatagrid({
    datagrid(df) %>%
      grid_click(
        inputId = "click"
      )
  })
  
observeEvent(input$click,{
  showModal(modalDialog(title = "test", print(input$click)))
  
  
})
}

shinyApp(ui, server)
```

I think that adding  ` {priority: "event"}` to all `Shiny.setInputValue` will solve the problem

**Comment by pvictor** [comment]
Yes you're right! Please re-install from GitHub it should be ok.

**Comment by fsty** [comment]
Works! thank you
