### ISSUE TITLE
tui-editor

### ISSUE THREAD

**Issue by jwijffels** [dreamRs/toastui#27]
Hello,

I'd be interested in having a markdown editor in Shiny. 
I've looked to available htmlwidgets but couldn't directly find one.
I wonder if you are open to a pull request regarding the integration of the tui-editor https://ui.toast.com/tui-editor 
If so, let me know if you have any preferences styles of code, small/large commits/... and I'll try to stick to it (I did some htmlwidget work with this R package https://cran.r-project.org/package=recogito but maybe you have a different way of doing things)
If you want it in another R package, let me know as well. 

FYI. The developments which I am interested in integrating is the possibility to have the tui-editor and make sure you can add dynamically generated markdown (e.g. flextable) in the editor.

Jan

**Comment by pvictor** [comment]
Hello Jan,

Sure, that'll be a great addition.
I don't have strict rules for commit / code, but I try to follow these rules : 
* small and descriptive commit
* code according to https://style.tidyverse.org/

For javascript code I use package [packer](https://github.com/JohnCoene/packer) to manage assets, let me know if you need more info on this.

For integrating custom content like flextable that's maybe possible in shiny via https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md#-custom-block-node-and-html-node, but it has to be tested!

Victor

**Comment by jwijffels** [comment]
Hello Victor. Thanks for the feedback. I've brewed up a working solution yesterday evening. I still need to think further if it makes sense to add it here as it will have some custom / non-generic components. Let me think about this further before bugging you.
