### ISSUE TITLE
Setting Visible Event Counts in cal_month_props()

### ISSUE THREAD

**Issue by connorH982** [dreamRs/toastui#29]
Hello,

I was looking to set the number of visible events in a calendar -- how many would appear in a day without needing to click a "show more" drop down. This appears to be an option in the JavaScript documentation: https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#monthvisibleeventcount

However it doesn't seem to work if I try to set it as an additional option.

Either (a) the cal_month_options() function throws an error if I pass it as an additional option:

```

calendar(rbind(cal_demo_data(),cal_demo_data(),cal_demo_data()), navigation = TRUE, defaultDate = Sys.Date()) %>%
    cal_month_options(
        startDayOfWeek  = 1, 
        narrowWeekend = TRUE,
        visibleEventCount = 10
    ) %>% 
    cal_props(cal_demo_props())


```

Or (b), using a very slightly modified function removing that check, it gets ignored:

```
cal_month_options2 <- function(cal,
                                   startDayOfWeek = NULL,
                                   daynames = NULL,
                                   narrowWeekend = NULL,
                                   visibleWeeksCount = NULL,
                                   isAlways6Week = NULL,
                                   workweek = NULL,
                                   visibleScheduleCount = NULL,
                                   scheduleFilter = NULL,
                                   visibleEventCount = NULL,
                                   ...) {
      #check_cal(cal, "cal_month_options")
      toastui:::.widget_options(
        widget = cal,
        name_opt = "month",
        startDayOfWeek = startDayOfWeek,
        dayNames = daynames,
        narrowWeekend = narrowWeekend,
        visibleWeeksCount = visibleWeeksCount,
        isAlways6Weeks = isAlways6Week,
        workweek = workweek,
        visibleScheduleCount = visibleScheduleCount,
        scheduleFilter = scheduleFilter,
        visibleEventCount = visibleEventCount,
        ...
      )
    }

calendar(rbind(cal_demo_data(),cal_demo_data(),cal_demo_data()), navigation = TRUE, defaultDate = Sys.Date()) %>%
    cal_month_options2(
        startDayOfWeek  = 1, 
        narrowWeekend = TRUE,
        visibleEventCount = 10
    ) %>% 
    cal_props(cal_demo_props())


```

Just checking if there's a workaround if its intended, and flagging if that is not.

**Comment by andrewsrs** [comment]
This would be highly useful if it were implemented.

**Comment by pvictor** [comment]
Have you tried dev version ? Should work

**Comment by connorH982** [comment]
Hello, sorry for such a delayed response.

But just an fyi, this doesn't seem to work. At least after reinstalling with `remotes::install_github("dreamRs/toastui")`. No error, but it also doesn't have any effect when the calendar renders at all so far as I can tell.

Not sure if its related, but the new option added is listed as "visibleScheduleCount" but the linked Java documentation calls it "visibleEventCount".
