### ISSUE TITLE
Checkbox doesn't update renderCalendar()

### ISSUE THREAD

**Issue by MichalLauer** [dreamRs/toastui#31]
Hello Victor,
My calendar in shiny is not updated when a checkbox is changed. The only change happens when I first click on the checkbox (navigation disappears). All changes after that are ignored.
I'm using the latest version of toastui from Github (0.2.1.93).

```r
library(shiny)
library(toastui)
ui <- fillPage(
  checkboxInput("cal_navigation", "Navigation", T),
  calendarOutput("cal_main")
)
server <- shinyServer(function(input, output) {
  output$cal_main <- renderCalendar({
    calendar(cal_demo_data(),
      navigation = input$cal_navigation,
      defaultDate = Sys.Date()
    )
  })
})
shinyApp(ui, server)
```

DevTools in chrome show this exception:

![image](https://user-images.githubusercontent.com/20439350/212145355-b4b378b3-830d-46d0-8c6d-d6137b0699d6.png)

When I use a proxy to update the calendar, the same thing and error happens

```r
library(shiny)
library(toastui)
ui <- fillPage(
  checkboxInput("cal_navigation", "Navigation", T),
  calendarOutput("cal_main")
)
server <- shinyServer(function(input, output) {
  output$cal_main <- renderCalendar({
    calendar(cal_demo_data())
  })
  observeEvent(input$cal_navigation, {
    cal_proxy_options("cal_main", navigation = input$cal_navigation)
  })
})
shinyApp(ui, server)
```

Do you know what am I missing?
Thanks a lot!

**Comment by MichalLauer** [comment]
My investigation so far:

When `input$cal_navigation` is used within the `calendar()` call, the navigation can only be turned off (assuming the default value for the checkbox is `TRUE`). Once it is turned off, the \<div\> that holds the navigation element _(id cal_main_menu)_ is removed, and checking the box again won't re-insert the navigation (won't add the div back).

When I use `cal_proxy_options()` to update the navigation, nothing happens. This is quite strange because when I use the example given in [examples/cal-proxy-options.R](https://github.com/dreamRs/toastui/blob/ea47b5f1d31ad3700d1710b5e69eb3dd2f18fabf/examples/cal-proxy-options.R), the month options are being updated. I'm thinking if this has something to do with the fact that month options are passed as a named list

```r
cal_proxy_options("mycal", month = list(narrowWeekend = input$narrowWeekend))
```

but data for a calendar is passed as an unnamed argument/list

```r
cal_proxy_options("cal_main", navigation = input$cal_navigation)
# or
cal_proxy_options("cal_main", list(navigation = input$cal_navigation))
```

The JSON that is then sent further has a different structure.

 month update - **presumably** the correct format
```json
{
   "custom":{
      "proxy-toastui-calendar-options":{
         "id":"mycal",
         "data":{
            "options":{
               "month":{
                  "workweek":false
               }
            }
         }
      }
   }
}
```

calendar update with an unnamed parameter is by one level shallower
```json
{
   "custom":{
      "proxy-toastui-calendar-options":{
         "id":"cal_main",
         "data":{
            "options":{
               "navigation":true
            }
         }
      }
   }
}
```
calendar update with an unnamed list contains unnamed array
```json
{
   "custom":{
      "proxy-toastui-calendar-options":{
         "id":"cal_main",
         "data":{
            "options":[
               {
                  "navigation":true
               }
            ]
         }
      }
   }
}
```

I'm currently trying to investigate what should be the correct format in JS, but it may take a while. Will update if I find something new and usefull.

**Comment by pvictor** [comment]
Hello,
Indeed I can reproduce the error, this argument was not intended to be used like that and that's not a functionnality from the JS lib tui.calendar but it's something built in the htmlwidget itself for cases where you can't interact with the calendar (rmarkdown document, RStudio viewer), in shiny apps you can interact with the calendar through the proxy so you can create your own components and toggle their display as you want (there's an example [here](https://dreamrs.github.io/toastui/reference/calendar-proxy-navigate.html) to navigate the calendar with classic actionButtons).
I'll look if we can not remove the div containing the buttons to solve this

Victor
