### ISSUE TITLE
Increase size of "more" popup

### ISSUE THREAD

**Issue by ivelasq** [dreamRs/toastui#39]
First, thank you so much for this package! It is incredible.

I created a calendar but when there are multiple items on the same day, the popup box that appears when you click "more" is quite small. Is there a way to increase the size so that scrolling is not necessary?

Thanks again.

**Comment by pvictor** [comment]
Hello,

You can use `cal_theme()` to modify different aspect of the calendar, for example : 

```r
library(toastui)
rbind(
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data(),
  cal_demo_data()
) |> 
  calendar() |>
  cal_theme(
    month = list(
      moreView = list(
        border = "2px solid blue",
        boxShadow = '0 2px 6px 0 grey',
        backgroundColor = 'white',
        width = 350,
        height = 480
      )
    )
  )
```

See https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/theme.md#month-moreview for more details.

Victor

**Comment by ivelasq** [comment]
Thank you so much! I really appreciate it.
