### ISSUE TITLE
[bug] `eventView = c("time")` doesn't work

### ISSUE THREAD

**Issue by toxin98** [dreamRs/toastui#42]
It seems `eventView` doesn't work if I only want to see the time grid

```
calendar(
  cal_demo_data(),
  view = "week",
  navigation = TRUE,
  isReadOnly = FALSE,
  useCreationPopup = TRUE
) %>%
  cal_week_options(
    eventView = c("time"),
    taskView = FALSE
  )
```

**Comment by pvictor** [comment]
Which version do you use ? 

With your code I see : 

![image](https://github.com/dreamRs/toastui/assets/4415580/6f3bbd70-6960-46e3-a115-35ebda8d8362)

**Comment by toxin98** [comment]
Sorry it's working now, I don't know why it didn't work at that time, anyway, thanks for the help!
