### ISSUE TITLE
navigation stops working if many events

### ISSUE THREAD

**Issue by nick-youngblut** [dreamRs/toastui#45]
I am displaying >100 events across 5 calendars. 

If I navigate to an earlier month (e.g., Dec 2023 from starting at Feb 2024), the calendar not longer updates and stays frozen on the same set of events, regards of which month I navigate to. If I try to switch the calendar view (month to week), no events are shown in the different view. I cannot switch back to the month view. No matter what, the calendar just freezes up permanently.

If I move forward in time, there are only a few events, so the calendar does not freeze. I've tried moving forward many months, but there is no issue.

I've tried starting with the week view, and the week of `2024-01-21 ~ 2024-01-27` always causes the calendar to freeze and permanently show the `2024-01-21 ~ 2024-01-27` week events, regardless of which week I navigate to.

![Screenshot 2024-02-29 at 2 31 39 PM](https://github.com/dreamRs/toastui/assets/2468572/ca857d93-b6d5-4eb7-b2b3-eeea9407d129)
![Screenshot 2024-02-29 at 2 31 46 PM](https://github.com/dreamRs/toastui/assets/2468572/539a7d2a-88b1-4d10-a83f-e31543a306ca)
![Screenshot 2024-02-29 at 2 31 51 PM](https://github.com/dreamRs/toastui/assets/2468572/eeaedacd-fe89-4e9f-b10e-3a9e7adc73a2)

**Comment by nick-youngblut** [comment]
It's just 1 of the 5 calendars that is causing the issue. It appears to be the result of a "bad" event in the calendar for that week.

**Comment by nick-youngblut** [comment]
The issue was due to one Google Calendar event, in which the creator never provided a title for the event, so it was just `(No Title)`. I added a title to the event, and now the calendar no longer freezes.

**Comment by nick-youngblut** [comment]
@pvictor this appears to be a bug. Have you made any updates to at least provide a warning to the developer, if this issue occurs (`No Title`)?

**Comment by pvictor** [comment]
Please provide a reproducible example of the issue and I'll fix what need fixing.
