### ISSUE TITLE
Unused icons and buttons in popup

### ISSUE THREAD

**Issue by royfrancis** [dreamRs/toastui#48]
What are these icons and buttons in popup? Can they be used/customized or else disabled?

![Screenshot 2024-04-27 at 22 57 32](https://github.com/dreamRs/toastui/assets/5083500/1fd9bbda-ecda-4642-b970-c98c432e65a2)

```
R 4.3.2
toastui 0.3.1
```

**Comment by royfrancis** [comment]
For now, I have decided to hide it with CSS.

```
.toastui-calendar-section-button,
.toastui-calendar-popup-section > .toastui-calendar-detail-item:nth-child(1),
.toastui-calendar-popup-section > .toastui-calendar-detail-item:nth-child(2) {
  display: none;
}
```

![Screenshot 2024-04-29 at 13 42 12](https://github.com/dreamRs/toastui/assets/5083500/7f75a8a5-a635-4f1b-900b-4c1d7f9d54d4)

**Comment by pvictor** [comment]
That's a good solution 👍
