### ISSUE TITLE
Inability to remove all day from scheduleView 

### ISSUE THREAD

**Issue by RoshanPShetty** [dreamRs/toastui#5]
Hello. I was going through the documentation to understand how to remove `All day` from `scheduleView`. However, despite doing `scheduleView = c('time')`, the `All day` section appears in the calendar. What seems to be the problem here?

Also, a quick note, the documentation says that the default value is FALSE in one place while it says it is TRUE in the other. I have provided the screenshots below for your reference. 
![image](https://user-images.githubusercontent.com/47758717/124043860-f830a400-d9d9-11eb-94f8-7236461992ac.png)
![image](https://user-images.githubusercontent.com/47758717/124043871-febf1b80-d9d9-11eb-90c3-43560b87d0d9.png)

**Comment by pvictor** [comment]
Hello,

Thanks, I've corrected the documentation.
To remove allday view, you can do:

```r
calendar(cal_demo_data("week"), view = "week", scheduleView = list("time"))
```

Note that the `list` is needed except if you re-install from GitHub, in that case you can just use `scheduleView = "time"`.

Victor

**Comment by RoshanPShetty** [comment]
Hi @pvictor. Thanks! It is working now!
