### ISSUE TITLE
Deleting multiple rows from schedules dataframe using cal_proxy_delete

### ISSUE THREAD

**Issue by RoshanPShetty** [dreamRs/toastui#6]
Hi. I wanted to delete the rows with the `title = P` from my `schedules` dataframe. I did see your example in the documentation. However, my calendar is `readonly`. 
I tried: 
```
observeEvent(input$update, {
    cal_proxy_delete(proxy = "cal", value = schedules[schedules$title == "P",])
  }).
```
The code above didn't work. So is it possible to delete multiple rows from the `schedules` dataframe using `cal_proxy_delete`? If so, could you please help me out?

![image](https://user-images.githubusercontent.com/47758717/124027447-e55da580-d9c0-11eb-838f-fde8977192b3.png)

**Comment by pvictor** [comment]
If you re-install from GitHub, this should work.
Note that for deleting schedules, you must give them a unique `id` and a `calendarId` when you create them and the date you use to delete them must have those columns.

Here's an example:

```r
library(shiny)
library(toastui)

# create schedules data.frame
schedules <- cal_demo_data()
# add an ID column
schedules$id <- seq_len(nrow(schedules))

ui <- fluidPage(
  tags$h2("Delete multiple schedules"),
  
  actionButton("delete", "Delete schedules"),
  
  calendarOutput("my_calendar")
)

server <- function(input, output) {
  
  output$my_calendar <- renderCalendar({
    calendar(
      schedules,
      defaultDate = Sys.Date(),
      useNavigation = TRUE,
      isReadOnly = FALSE,
      useCreationPopup = TRUE
    )
  })
  
  
  observeEvent(input$delete, {
    cal_proxy_delete("my_calendar", schedules[schedules$calendarId != 1, ])
  })
  
}

shinyApp(ui = ui, server = server)
```

Victor

**Comment by RoshanPShetty** [comment]
@pvictor Thanks a lot! It works!
